export const processorsData = [
  {
    id: 1,
    name: "Intel Core i9-12900K",
    img: "https://www.startech.com.bd/image/cache/catalog/processor/AMD/ryzen-3-4100/amd-ryzen-3-4100-01-500x500.jpg",
    speed: "3.2 GHz",
    cacheL2: "12 MB",
    cacheL3: "30 MB",
    cores: 16,
    threads: 24,
    memorySpeed: "4800 MHz",
    price: 55000,
    thermalDesignPower: "125W",
    integratedGraphics: "Intel UHD Graphics 770",
    warranty: "3 years",
    description: "High-performance processor ideal for gaming and content creation."
  },
  {
    id: 2,
    name: "AMD Ryzen 9 5900X",
    img: "https://www.startech.com.bd/image/cache/catalog/processor/amd/ryzen-5-2400g/ryzen-5-2400g-001-500x500.webp",
    speed: "3.7 GHz",
    cacheL2: "6 MB",
    cacheL3: "64 MB",
    cores: 12,
    threads: 24,
    memorySpeed: "3200 MHz",
    price: 45000,
    thermalDesignPower: "105W",
    integratedGraphics: "No",
    warranty: "3 years",
    description: "Excellent multi-threaded performance for gaming and productivity."
  },
  {
    id: 3,
    name: "Intel Core i7-12700K",
    img: "https://www.startech.com.bd/image/cache/catalog/processor/Intel/i7-11700/i7-11700-500x500.jpg",
    speed: "3.6 GHz",
    cacheL2: "11 MB",
    cacheL3: "25 MB",
    cores: 12,
    threads: 20,
    memorySpeed: "4800 MHz",
    price: 42000,
    thermalDesignPower: "125W",
    integratedGraphics: "Intel UHD Graphics 770",
    warranty: "3 years",
    description: "A great choice for gaming and high-performance tasks."
  },
  {
    id: 4,
    name: "AMD Ryzen 7 5800X",
    img: "https://www.startech.com.bd/image/cache/catalog/processor/AMD/ryzen-5-4500/amd-ryzen-5-4500-01-500x500.jpg",
    speed: "3.8 GHz",
    cacheL2: "4 MB",
    cacheL3: "32 MB",
    cores: 8,
    threads: 16,
    memorySpeed: "3200 MHz",
    price: 38000,
    thermalDesignPower: "105W",
    integratedGraphics: "No",
    warranty: "3 years",
    description: "Strong performance for gaming and content creation."
  },
  {
    id: 5,
    name: "Intel Core i5-12600K",
    img: "https://www.startech.com.bd/image/cache/catalog/processor/Intel/i5-10400/i5-10400-1-500x500.jpg",
    speed: "3.7 GHz",
    cacheL2: "9.5 MB",
    cacheL3: "20 MB",
    cores: 10,
    threads: 16,
    memorySpeed: "4800 MHz",
    price: 30000,
    thermalDesignPower: "125W",
    integratedGraphics: "Intel UHD Graphics 770",
    warranty: "3 years",
    description: "Balanced performance for gamers and creators."
  },
  {
    id: 6,
    name: "AMD Ryzen 5 5600X",
    img: "https://www.startech.com.bd/image/cache/catalog/processor/amd/ryzen-5-4600g/ryzen-5-4600g-500x500.jpg",
    speed: "3.7 GHz",
    cacheL2: "3 MB",
    cacheL3: "32 MB",
    cores: 6,
    threads: 12,
    memorySpeed: "3200 MHz",
    price: 27000,
    thermalDesignPower: "65W",
    integratedGraphics: "No",
    warranty: "3 years",
    description: "Great value CPU for gaming and everyday tasks."
  },
  {
    id: 7,
    name: "Intel Core i3-12100",
    img: "https://www.startech.com.bd/image/cache/catalog/processor/intel/i3-12100/i3-12100-500x500.jpg",
    speed: "3.3 GHz",
    cacheL2: "5 MB",
    cacheL3: "12 MB",
    cores: 4,
    threads: 8,
    memorySpeed: "4800 MHz",
    price: 18000,
    thermalDesignPower: "60W",
    integratedGraphics: "Intel UHD Graphics 730",
    warranty: "3 years",
    description: "Affordable option for basic computing tasks."
  },
  {
    id: 8,
    name: "AMD Ryzen 3 3300X",
    img: "https://www.startech.com.bd/image/cache/catalog/processor/AMD/ryzen-3500/ryzen-3500-500x500.jpg",
    speed: "3.8 GHz",
    cacheL2: "2 MB",
    cacheL3: "16 MB",
    cores: 4,
    threads: 8,
    memorySpeed: "3200 MHz",
    price: 16000,
    thermalDesignPower: "65W",
    integratedGraphics: "No",
    warranty: "3 years",
    description: "Solid performance for entry-level gaming."
  },
  {
    id: 9,
    name: "Intel Core i9-11900K",
    img: "https://www.startech.com.bd/image/cache/catalog/processor/intel/core-i3-10105/core-i3-10105-001-500x500.jpg",
    speed: "3.5 GHz",
    cacheL2: "10 MB",
    cacheL3: "16 MB",
    cores: 8,
    threads: 16,
    memorySpeed: "3200 MHz",
    price: 50000,
    thermalDesignPower: "125W",
    integratedGraphics: "Intel UHD Graphics 750",
    warranty: "3 years",
    description: "Top-tier performance for gaming and heavy multitasking."
  },
  {
    id: 10,
    name: "AMD Ryzen 9 3950X",
    img: "https://www.startech.com.bd/image/cache/catalog/processor/amd/ryzen-5-4600g/ryzen-5-4600g-500x500.jpg",
    speed: "3.5 GHz",
    cacheL2: "8 MB",
    cacheL3: "64 MB",
    cores: 16,
    threads: 32,
    memorySpeed: "3200 MHz",
    price: 60000,
    thermalDesignPower: "105W",
    integratedGraphics: "No",
    warranty: "3 years",
    description: "Exceptional performance for content creation and gaming."
  },
];


// src/data.js

export const coolersData = [
  {
    id: 1,
    name: "NZXT T120 RGB 120mm Air CPU Cooler White",
    type: "Air Cooler",
    compatibility: "Intel & AMD",
    fanSpeed: "2000 RPM",
    noiseLevel: "19 dBA",
    price: 3500,
    img: "https://www.startech.com.bd/image/cache/catalog/cpu-cooler/nzxt/t120-rgb-white/t120-rgb-white-01-500x500.webp",
    performance: 85,
  },
  {
    id: 2,
    name: "Arctic Freezer 4U-M Air CPU Cooler",
    type: "Air Cooler",
    compatibility: "Intel & AMD",
    fanSpeed: "1500 RPM",
    noiseLevel: "24.6 dBA",
    price: 8000,
    img: "https://www.startech.com.bd/image/cache/catalog/cpu-cooler/arctic/freezer-4u-m/freezer-4u-m-01-500x500.webp",
    performance: 95,
  },
  {
    id: 3,
    name: "Deepcool GAMMA ARCHER CPU Air Cooler",
    type: "Air Cooler",
    compatibility: "Intel & AMD",
    fanSpeed: "2400 RPM",
    noiseLevel: "30 dBA",
    price: 7000,
    img: "https://www.startech.com.bd/image/cache/catalog/cpu-cooler/deepcool/gamma-archer/gamma-archer-01-500x500.jpg",
    performance: 90,
  },
  {
    id: 4,
    name: "DeepCool ICE EDGE MINI FS V2.0 CPU Air Cooler",
    type: "Air Cooler",
    compatibility: "Intel & AMD",
    fanSpeed: "1500 RPM",
    noiseLevel: "24.3 dBA",
    price: 6500,
    img: "https://www.startech.com.bd/image/cache/catalog/cpu-cooler/deepcool/ice-edge-mini-fs-v2-0/ice-edge-mini-fs-v2-0-500x500.jpg",
    performance: 88,
  },
  {
    id: 5,
    name: "DeepCool AK620 High Performance Dual Tower CPU Cooler",
    type: "Liquid Cooler",
    compatibility: "Intel & AMD",
    fanSpeed: "2000 RPM",
    noiseLevel: "23.5 dBA",
    price: 6000,
    img: "https://www.startech.com.bd/image/cache/catalog/cpu-cooler/deepcool/ak620/ak620-01-500x500.jpg",
    performance: 92,
  },
  {
    id: 6,
    name: "Deepcool UD551 ARGB CPU Air Cooler",
    type: "Liquid Cooler",
    compatibility: "Intel & AMD",
    fanSpeed: "2800 RPM",
    noiseLevel: "29 dBA",
    price: 7500,
    img: "https://www.startech.com.bd/image/cache/catalog/cpu-cooler/deepcool/ud551/ud551-01-500x500.jpg",
    performance: 89,
  },
  {
    id: 7,
    name: "Corsair H100 RGB 240mm Liquid CPU Cooler",
    type: "Air Cooler",
    compatibility: "Intel & AMD",
    fanSpeed: "1400 RPM",
    noiseLevel: "26 dBA",
    price: 7000,
    img: "https://www.startech.com.bd/image/cache/catalog/cpu-cooler/corsair/h100/h100-rgb-01-500x500.jpg",
    performance: 87,
  },
  {
    id: 8,
    name: "1stplayer MT 240 Mothra ARGB Liquid CPU Cooler",
    type: "Liquid Cooler",
    compatibility: "Intel & AMD",
    fanSpeed: "2000 RPM",
    noiseLevel: "27 dBA",
    price: 6500,
    img: "https://www.startech.com.bd/image/cache/catalog/cpu-cooler/1stplayer/mt-240-mothra/mt-240-mothra-01-500x500.jpg",
    performance: 86,
  },
  {
    id: 9,
    name: "Thermaltake UX200 ARGB Lighting Air CPU Cooler",
    type: "Liquid Cooler",
    compatibility: "Intel & AMD",
    fanSpeed: "2000 RPM",
    noiseLevel: "24 dBA",
    price: 5500,
    img: "https://www.startech.com.bd/image/cache/catalog/cpu-cooler/thermaltake/ux200/ux200-500x500.jpg",
    performance: 85,
  },
  {
    id: 10,
    name: "Arctic Freezer 4U-M Air CPU Cooler",
    type: "Air Cooler",
    compatibility: "Intel & AMD",
    fanSpeed: "1200 RPM",
    noiseLevel: "19.5 dBA",
    price: 4000,
    img: "https://www.startech.com.bd/image/cache/catalog/cpu-cooler/arctic/freezer-4u-m/freezer-4u-m-01-500x500.webp",
    performance: 83,
  },
];

export const motherboardData = [
  {
    id: 1,
    name: 'GIGABYTE H410M H V2 10th Gen Micro ATX Motherboard',
    img: 'https://www.startech.com.bd/image/cache/catalog/motherboard/gigabyte/h410m-h-v2/h410m-h-v2-01-500x500.webp',
    socket: 'LGA 1151',
    chipset: 'Z490',
    formFactor: 'ATX',
    memorySlots: 4,
    maxMemory: '128 GB',
    price: 10000,
    performance: 90,
  },
  {
    id: 2,
    name: 'Asus PRIME B450M-K II DDR4 AMD AM4 micro ATX Motherboard',
    img: 'https://www.startech.com.bd/image/cache/catalog/motherboard/asus/prime-b450m-k-ii/prime-b450m-k-ii-01-500x500.webp',
    socket: 'AM4',
    chipset: 'B450',
    formFactor: 'Micro ATX',
    memorySlots: 2,
    maxMemory: '64 GB',
    price: 8000,
    performance: 80,
  },
  {
    id: 3,
    name: 'MSI H510M-A PRO Intel 10th Gen and 11th Gen Micro-ATX Motherboard',
    img: 'https://www.startech.com.bd/image/cache/catalog/motherboard/msi/h510m-a-pro/h510m-a-pro-01-500x500.jpg',
    socket: 'LGA 1200',
    chipset: 'Z590',
    formFactor: 'ATX',
    memorySlots: 4,
    maxMemory: '128 GB',
    price: 12000,
    performance: 95,
  },
  {
    id: 4,
    name: 'ASRock H510M-HDV/M.2 10th and 11th Gen Micro ATX Motherboard',
    img: 'https://www.startech.com.bd/image/cache/catalog/motherboard/asrock/h510m-hdv-m-2/h510m-hdv-m-2-500x500.jpg',
    socket: 'AM4',
    chipset: 'X570',
    formFactor: 'ATX',
    memorySlots: 4,
    maxMemory: '128 GB',
    price: 15000,
    performance: 93,
  },
  {
    id: 5,
    name: 'BIOSTAR B550MH DDR4 AMD AM4 Micro ATX Motherboard',
    img: 'https://www.startech.com.bd/image/cache/catalog/motherboard/biostar/b550mh/b550mh-01-500x500.webp',
    socket: 'LGA 1151',
    chipset: 'B460',
    formFactor: 'Micro ATX',
    memorySlots: 2,
    maxMemory: '64 GB',
    price: 7000,
    performance: 75,
  },
  {
    id: 6,
    name: 'GIGABYTE H610M H DDR4 Micro ATX Motherboard',
    img: 'https://www.startech.com.bd/image/cache/catalog/motherboard/gigabyte/h610m-h-ddr4/h610m-h-ddr4-01-500x500.jpg',
    socket: 'LGA 2066',
    chipset: 'X299',
    formFactor: 'ATX',
    memorySlots: 8,
    maxMemory: '256 GB',
    price: 18000,
    performance: 92,
  },
  {
    id: 7,
    name: 'ASUS TUF GAMING A620M-PLUS AMD AM5 Micro-ATX Motherboard',
    img: 'https://www.startech.com.bd/image/cache/catalog/motherboard/asus/tuf-gaming-a620m-plus/tuf-gaming-a620m-plus-01-500x500.webp',
    socket: 'LGA 1200',
    chipset: 'H510',
    formFactor: 'Mini ITX',
    memorySlots: 2,
    maxMemory: '64 GB',
    price: 6000,
    performance: 70,
  },
  {
    id: 8,
    name: 'ASUS ROG MAXIMUS Z790 FORMULA ATX Motherboar',
    img: 'https://www.startech.com.bd/image/cache/catalog/motherboard/asus/rog-maximus-z790-formula/rog-maximus-z790-formula-001-500x500.webp',
    socket: 'AM4',
    chipset: 'B550',
    formFactor: 'ATX',
    memorySlots: 4,
    maxMemory: '128 GB',
    price: 9000,
    performance: 85,
  },
  {
    id: 9,
    name: 'Gigabyte B550 AORUS ELITE Gaming AMD Motherboard',
    img: 'https://www.startech.com.bd/image/cache/catalog/motherboard/gigabyte/aorus-b550-elite/aorus-b550-elite-500x500.jpg',
    socket: 'LGA 2011',
    chipset: 'C602',
    formFactor: 'E-ATX',
    memorySlots: 8,
    maxMemory: '128 GB',
    price: 20000,
    performance: 88,
  },
  {
    id: 10,
    name: 'MSI MEG Z790 ACE MAX DDR5 E-ATX Motherboard',
    img: 'https://www.startech.com.bd/image/cache/catalog/motherboard/msi/meg-z790-ace-max/meg-z790-ace-max-001-500x500.webp',
    socket: 'LGA 1150',
    chipset: 'H97',
    formFactor: 'Micro ATX',
    memorySlots: 4,
    maxMemory: '32 GB',
    price: 5000,
    performance: 65,
  },
];
export const ramData = [
  {
    id: 1,
    name: 'Corsair Vengeance LPX 16GB',
    img: 'https://www.startech.com.bd/image/cache/catalog/ram/cosair/vengeance-16gb-ddr4/16gb-ddr4-500x500.jpg',
    capacity: '16GB',
    speed: '3200MHz',
    type: 'DDR4',
    voltage: '1.35V',
    channels: 'Dual Channel',
    price: 6000,
    performance: 85,
  },
  {
    id: 2,
    name: 'G.Skill Ripjaws V 16GB',
    img: 'https://www.startech.com.bd/image/cache/catalog/ram/gskill/ripjaws-v-16gb/ripjaws-v-16gb-500x500.jpg',
    capacity: '16GB',
    speed: '3200MHz',
    type: 'DDR4',
    voltage: '1.35V',
    channels: 'Dual Channel',
    price: 5800,
    performance: 80,
  },
  {
    id: 3,
    name: 'Gigabyte AORUS 8GB 3200MHz RGB RAM',
    img: 'https://www.startech.com.bd/image/cache/catalog/ram/gigabyte/gigabyte-aorus-rgb-8gb/gigabyte-aorus-rgb-8gb-3-500x500.jpg',
    capacity: '8GB',
    speed: '3200MHz',
    type: 'DDR4',
    voltage: '1.35V',
    channels: 'Dual Channel',
    price: 5900,
    performance: 82,
  },
  {
    id: 4,
    name: 'TEAM NIGHT HAWK UD 8GB 3200MHz RGB DDR4 Desktop RAM',
    img: 'https://www.startech.com.bd/image/cache/catalog/ram/team/night-hawk-ud/night-hawk-ud-500x500.jpg',
    capacity: '16GB',
    speed: '3200MHz',
    type: 'DDR4',
    voltage: '1.35V',
    channels: 'Dual Channel',
    price: 5700,
    performance: 78,
  },
  {
    id: 5,
    name: 'Kingston FURY Beast RGB 16GB 6000Mhz DDR5 EXPO Desktop RAM',
    img: 'https://www.startech.com.bd/image/cache/catalog/ram/kingston/fury-beast-rgb/fury-beast-rgb-04-500x500.webp',
    capacity: '16GB',
    speed: '3200MHz',
    type: 'DDR4',
    voltage: '1.35V',
    channels: 'Dual Channel',
    price: 5600,
    performance: 76,
  },
  {
    id: 6,
    name: 'Apacer NOX RGB 16GB DDR4 3600MHz RAM',
    img: 'https://www.startech.com.bd/image/cache/catalog/ram/apacer/nox-16gb-3600mhz/Nox-16gb-3200mhz.jpg-1000x1000-500x500.jpg',
    capacity: '16GB',
    speed: '3200MHz',
    type: 'DDR4',
    voltage: '1.35V',
    channels: 'Dual Channel',
    price: 5900,
    performance: 79,
  },
  {
    id: 7,
    name: 'TEAM T-FORCE DELTA RGB 32GB (16GBx2) 7200MHz DDR5 Gaming RAM',
    img: 'https://www.startech.com.bd/image/cache/catalog/ram/team/delta-rgb/delta-rgb-01-500x500.webp',
    capacity: '16GB',
    speed: '3600MHz',
    type: 'DDR4',
    voltage: '1.35V',
    channels: 'Dual Channel',
    price: 6500,
    performance: 90,
  },
  {
    id: 8,
    name: 'G.Skill Trident Z5 RGB 16GB DDR5 7200MHz Desktop RAM',
    img: 'https://www.startech.com.bd/image/cache/catalog/ram/gskill/trident-z5-rgb/trident-z5-rgb-01-500x500.webp',
    capacity: '32GB',
    speed: '3200MHz',
    type: 'DDR4',
    voltage: '1.35V',
    channels: 'Dual Channel',
    price: 12000,
    performance: 95,
  },
  {
    id: 9,
    name: 'Kimtigo WOLFRINE 8GB 3200MHz DDR4 UDIMM Desktop RAM',
    img: 'https://www.startech.com.bd/image/cache/catalog/ram/kimtigo/wolfrine-8gb/wolfrine-8gb-03-500x500.webp',
    capacity: '16GB',
    speed: '3600MHz',
    type: 'DDR4',
    voltage: '1.35V',
    channels: 'Dual Channel',
    price: 7000,
    performance: 88,
  },
  {
    id: 10,
    name: 'Corsair DOMINATOR PLATINUM RGB 16GB DDR5 7200MHz Desktop RAM',
    img: 'https://www.startech.com.bd/image/cache/catalog/ram/cosair/dominator-platinum-rgb-ddr5/dominator-platinum-rgb-ddr5-04-500x500.webp',
    capacity: '16GB',
    speed: '3200MHz',
    type: 'DDR4',
    voltage: '1.35V',
    channels: 'Dual Channel',
    price: 5500,
    performance: 75,
  },
];
export const storageData = [
  {
    id: 1,
    name: 'Samsung 970 EVO Plus 1TB',
    img: 'https://www.startech.com.bd/image/cache/catalog/ssd/samsung/970-evo-plus-1tb/970-evo-plus-1tb-500x500.jpg',
    type: 'SSD',
    capacity: '1TB',
    readSpeed: '3500 MB/s',
    writeSpeed: '3300 MB/s',
    interface: 'NVMe',
    price: 12000,
    performance: 95,
  },
  {
    id: 2,
    name: 'Thunderobot TR5000 512GB NVME Gen4 SSD',
    img: 'https://www.startech.com.bd/image/cache/catalog/ssd/thunderobot/tr5000/tr5000-01-500x500.webp',
    type: 'SSD',
    capacity: '500GB',
    readSpeed: '560 MB/s',
    writeSpeed: '510 MB/s',
    interface: 'SATA III',
    price: 6000,
    performance: 80,
  },
  {
    id: 3,
    name: 'Western Digital Blue 1TB',
    img: 'https://www.startech.com.bd/image/cache/catalog/ssd/western-digital/SN550/81e7Z2Y385L._AC_SL1500_-500x500.jpg',
    type: 'HDD',
    capacity: '1TB',
    readSpeed: '150 MB/s',
    writeSpeed: '140 MB/s',
    interface: 'SATA III',
    price: 4000,
    performance: 70,
  },
  {
    id: 4,
    name: 'Seagate Barracuda 2TB',
    img: 'https://www.startech.com.bd/image/cache/catalog/hdd/seagate/2tb-hdd/2tb-hdd-1-500x500.jpg',
    type: 'HDD',
    capacity: '2TB',
    readSpeed: '180 MB/s',
    writeSpeed: '170 MB/s',
    interface: 'SATA III',
    price: 5000,
    performance: 75,
  },
  {
    id: 5,
    name: 'Lexar NS100 1TB 2.5 inch Gray SATA III SSD',
    img: 'https://www.startech.com.bd/image/cache/catalog/ssd/lexar/ns100-256gb/ns100-256gb-500x500.jpg',
    type: 'SSD',
    capacity: '1TB',
    readSpeed: '2200 MB/s',
    writeSpeed: '2000 MB/s',
    interface: 'NVMe',
    price: 9000,
    performance: 85,
  },
  {
    id: 6,
    name: 'Team CLASSIC C47 1TB M.2 2280 PCIe Gen4x4 NVMe SSD',
    img: 'https://www.startech.com.bd/image/cache/catalog/ssd/team/classic-c47/classic-c47-01-500x500.webp',
    type: 'SSD',
    capacity: '480GB',
    readSpeed: '535 MB/s',
    writeSpeed: '450 MB/s',
    interface: 'SATA III',
    price: 5000,
    performance: 78,
  },
  {
    id: 7,
    name: 'Toshiba X300 4TB',
    img: 'https://www.startech.com.bd/image/cache/catalog/hdd/toshiba/x300/x300-1-500x500.jpg',
    type: 'HDD',
    capacity: '4TB',
    readSpeed: '190 MB/s',
    writeSpeed: '180 MB/s',
    interface: 'SATA III',
    price: 8000,
    performance: 72,
  },
  {
    id: 8,
    name: 'Transcend 250H 1TB M.2 2280 NVMe PCIe Gen4 x4 SSD',
    img: 'https://www.startech.com.bd/image/cache/catalog/ssd/transcend/250h/250h-01-500x500.webp',
    type: 'SSD',
    capacity: '1TB',
    readSpeed: '550 MB/s',
    writeSpeed: '520 MB/s',
    interface: 'SATA III',
    price: 10000,
    performance: 90,
  },
  {
    id: 9,
    name: 'Seagate FireCuda 530 1TB Gen4 M.2 2280 PCIe NVMe Gaming SSD',
    img: 'https://www.startech.com.bd/image/cache/catalog/ssd/seagate/firecuda-530/firecuda-530-01-500x500.webp',
    type: 'HDD',
    capacity: '500GB',
    readSpeed: '150 MB/s',
    writeSpeed: '140 MB/s',
    interface: 'SATA III',
    price: 3000,
    performance: 68,
  },
  {
    id: 10,
    name: 'Acer FA200 1TB M.2 NVMe PCIe Gen4 x 4 SSD',
    img: 'https://www.startech.com.bd/image/cache/catalog/ssd/acer/fa200/fa200-1tb-01-500x500.webp',
    type: 'SSD',
    capacity: '2TB',
    readSpeed: '5400 MB/s',
    writeSpeed: '5000 MB/s',
    interface: 'NVMe',
    price: 15000,
    performance: 92,
  },
];
export const gpusData = [
  {
    id: 1,
    name: 'NVIDIA GeForce RTX 3060',
    img: 'https://www.startech.com.bd/image/cache/catalog/graphics-card/msi/rtx-3060-ventus-2x/rtx-3060-ventus-2x-01-500x500.jpg',
    memory: '12GB',
    coreClock: '1320 MHz',
    boostClock: '1777 MHz',
    cudaCores: '3584',
    interface: 'PCIe 4.0',
    price: 30000,
    performance: 90,
  },
  {
    id: 2,
    name: 'AMD Radeon RX 6700 XT',
    img: 'https://www.startech.com.bd/image/cache/catalog/graphics-card/sapphire/rx-6700-xt-gaming-oc/rx-6700-xt-gaming%20oc-01-500x500.jpg',
    memory: '12GB',
    coreClock: '2321 MHz',
    boostClock: '2581 MHz',
    cudaCores: '2560',
    interface: 'PCIe 4.0',
    price: 35000,
    performance: 92,
  },
  {
    id: 3,
    name: 'MSI GeForce GT 1030 4GD4 LP OC 4GB Graphics Card',
    img: 'https://www.startech.com.bd/image/cache/catalog/graphics-card/msi/geforce-gt-1030-4gd4-lp-oc-4gb/geforce-gt-1030-4gd4-lp-oc-4gb-01-500x500.webp',
    memory: '8GB',
    coreClock: '1500 MHz',
    boostClock: '1725 MHz',
    cudaCores: '5888',
    interface: 'PCIe 4.0',
    price: 40000,
    performance: 95,
  },
  {
    id: 4,
    name: 'Zotac Gaming GeForce GTX 1650 AMP Core 4GB GDDR6 Graphics Card',
    img: 'https://www.startech.com.bd/image/cache/catalog/graphics-card/zotac/gaming-gtx-1650-amp/gaming-gtx-1650-amp-500x500.jpg',
    memory: '16GB',
    coreClock: '1815 MHz',
    boostClock: '2105 MHz',
    cudaCores: '3840',
    interface: 'PCIe 4.0',
    price: 50000,
    performance: 93,
  },
  {
    id: 5,
    name: 'OCPC GeForce RTX 3060 12GB GDDR6 Graphics Card',
    img: 'https://www.startech.com.bd/image/cache/catalog/graphics-card/ocpc/rtx-3060-12gb/rtx-3060-12gb-01-500x500.webp',
    memory: '10GB',
    coreClock: '1440 MHz',
    boostClock: '1710 MHz',
    cudaCores: '8704',
    interface: 'PCIe 4.0',
    price: 70000,
    performance: 98,
  },
  {
    id: 6,
    name: 'GIGABYTE GeForce RTX 4060 EAGLE OC 8G GDDR6 Graphics Card',
    img: 'https://www.startech.com.bd/image/cache/catalog/graphics-card/gigabyte/geforce-rtx-4060-eagle-oc-8g/geforce-rtx-4060-eagle-oc-8g-01-500x500.webp',
    memory: '16GB',
    coreClock: '1825 MHz',
    boostClock: '2250 MHz',
    cudaCores: '5120',
    interface: 'PCIe 4.0',
    price: 80000,
    performance: 96,
  },
  {
    id: 7,
    name: 'Sapphire PURE AMD Radeon RX 7700 XT 12GB Frostpunk 2 Edition GDDR6 Gaming Graphics Card',
    img: 'https://www.startech.com.bd/image/cache/catalog/graphics-card/sapphire/pure-amd-radeon-rx-7700-xt-12gb-frostpunk-2-edition/pure-amd-radeon-rx-7700-xt-12gb-frostpunk-2-edition-01-500x500.webp',
    memory: '8GB',
    coreClock: '1550 MHz',
    boostClock: '1777 MHz',
    cudaCores: '2048',
    interface: 'PCIe 4.0',
    price: 25000,
    performance: 85,
  },
  {
    id: 8,
    name: 'PNY GeForce RTX 4060 Ti 8GB XLR8 Gaming VERTO EPIC-X RGB Triple Fan GDDR6 Graphics Card',
    img: 'https://www.startech.com.bd/image/cache/catalog/graphics-card/pny/rtx-4060-ti-8gb-xlr8-gaming-verto-epic-x-rgb-triple-fan/rtx-4060-ti-8gb-xlr8-gaming-verto-epic-x-rgb-triple-fan-01-500x500.webp',
    memory: '6GB',
    coreClock: '1375 MHz',
    boostClock: '1560 MHz',
    cudaCores: '2304',
    interface: 'PCIe 4.0',
    price: 20000,
    performance: 80,
  },
  {
    id: 9,
    name: 'GIGABYTE GeForce RTX 4090 AERO OC 24G GDDR6X Graphics Card',
    img: 'https://www.startech.com.bd/image/cache/catalog/graphics-card/gigabyte/geforce-rtx-4090-aero-oc-24g/geforce-rtx-4090-aero-oc-24g-01-500x500.webp',
    memory: '6GB',
    coreClock: '1530 MHz',
    boostClock: '1785 MHz',
    cudaCores: '1408',
    interface: 'PCIe 3.0',
    price: 18000,
    performance: 75,
  },
  {
    id: 10,
    name: 'Colorful GeForce RTX 4080 16GB NB EX-V GDDR6X Graphics Card',
    img: 'https://www.startech.com.bd/image/cache/catalog/graphics-card/colorful/geforce-rtx-4080-16gb-nb-ex-v/geforce-rtx-4080-16gb-nb-ex-v-01-500x500.webp',
    memory: '4GB',
    coreClock: '1607 MHz',
    boostClock: '1845 MHz',
    cudaCores: '1408',
    interface: 'PCIe 4.0',
    price: 15000,
    performance: 70,
  },
];
// Keyboards data
export const keyboardsData = [
  {
    id: 1,
    name: 'T-WOLF T15 104 Keys USB Wired Keyboard',
    img: 'https://www.startech.com.bd/image/cache/catalog/keyboard/t-wolf/t15/t15-01-228x228.webp',
    switchType: 'GX Blue Clicky',
    rgbLighting: true,
    connection: 'Wired',
    price: 15000,
  },
  {
    id: 2,
    name: 'Meetion MT-K9320 Waterproof Backlit Gaming Keyboard',
    img: 'https://www.startech.com.bd/image/cache/catalog/keyboard/meetion/mt-k9320/mt-k9320-01-228x228.jpg',
    switchType: 'Cherry MX Speed',
    rgbLighting: true,
    connection: 'Wired',
    price: 18000,
  },
  {
    id: 3,
    name: 'Meetion MT-K800 Colored Big Keys Kids Keyboard',
    img: 'https://www.startech.com.bd/image/cache/catalog/keyboard/meetion/mt-k800/mt-k800-01-228x228.jpg',
    switchType: 'Razer Green',
    rgbLighting: true,
    connection: 'Wireless',
    price: 20000,
  },
  {
    id: 4,
    name: 'Havit KB878L Gamenote USB Multi-Function Backlit Keyboard',
    img: 'https://www.startech.com.bd/image/cache/catalog/keyboard/havit/kb878l/kb878l-01-228x228.webp',
    switchType: 'OmniPoint',
    rgbLighting: true,
    connection: 'Wired',
    price: 19000,
  },
  {
    id: 5,
    name: 'Redragon A130 Pudding 104 Keys Standard Doubleshot PBT Keycap Set White',
    img: 'https://www.startech.com.bd/image/cache/catalog/keyboard/redragon/a130-pudding/a130-pudding-white-228x228.jpg',
    switchType: 'HyperX Red',
    rgbLighting: true,
    connection: 'Wired',
    price: 12000,
  },
  {
    id: 6,
    name: 'Havit KB876L USB Multi-Function Backlit Gaming Keyboard',
    img: 'https://www.startech.com.bd/image/cache/catalog/keyboard/havit/kb876l/kb876l-01-228x228.webp',
    switchType: 'GL Tactile',
    rgbLighting: true,
    connection: 'Wireless',
    price: 19000,
  },
  {
    id: 7,
    name: 'Havit KB389L Mechanical Gaming Keyboard & Mouse Combo',
    img: 'https://www.startech.com.bd/image/cache/catalog/keyboard/havit/kb389l/kb389l-01-228x228.webp',
    switchType: 'Cherry MX Red',
    rgbLighting: true,
    connection: 'Wired',
    price: 7000,
  },
  {
    id: 8,
    name: 'Rapoo V500PRO Backlit Wired Yellow-Blue Mechanical Gaming Keyboard',
    img: 'https://www.startech.com.bd/image/cache/catalog/keyboard/Rapoo/v500pro/v500pro-01-228x228.webp',
    switchType: 'Opto-Mechanical',
    rgbLighting: true,
    connection: 'Wired',
    price: 22000,
  },
  {
    id: 9,
    name: 'Rapoo V500 PRO Backlit USB Mechanical Gaming Keyboard Purple',
    img: 'https://www.startech.com.bd/image/cache/catalog/keyboard/rapoo/v500pro/purple/v500-pro-purple-01-228x228.jpg',
    switchType: 'Cherry MX Brown',
    rgbLighting: true,
    connection: 'Wired',
    price: 13000,
  },
  {
    id: 10,
    name: 'Fantech Max Core MK852 Sakura Edition Mechanical USB Gaming Keyboard',
    img: 'https://www.startech.com.bd/image/cache/catalog/keyboard/fantech/mk852/sakura-edition/max-core-mk852-sakura-1-228x228.jpg',
    switchType: 'ROG RX Red',
    rgbLighting: true,
    connection: 'Wired',
    price: 16000,
  },
];

// Printers data
export const printersData = [
  {
    id: 1,
    name: 'Rongta RPP300BU Portable Mini 80mm Pocket Mobile POS Thermal Receipt Printer with Bluetooth+USB interfaces (Orange-Black Color)',
    img: 'https://ryans.com/storage/products/main/rongta-rpp300bu-portable-mini-80mm-pocket-mobile-11722152111.webp',
    type: 'Laser',
    color: 'Black & White',
    connectivity: 'Ethernet, USB',
    price: 25000,
  },
  {
    id: 2,
    name: 'Xprinter XP-E260M 80mm Black Thermal POS Receipt Printer',
    img: 'https://www.ryans.com/storage/products/small/xprinter-xp-e260m-80mm-black-thermal-pos-receipt-11705823831.webp',
    type: 'Inkjet',
    color: 'Color',
    connectivity: 'Wi-Fi, USB',
    price: 16000,
  },
  {
    id: 3,
    name: 'Rongta RP80 IV-USE-G / RP804-USE POS Printer (USB+ Serial+Ethernet)',
    img: 'https://ryans.com/storage/products/main/zkteco-zkp5808-black-portable-thermal-pos-11706936928.webp',
    type: 'Laser',
    color: 'Black & White',
    connectivity: 'Wi-Fi, USB',
    price: 22000,
  },
  {
    id: 4,
    name: 'Rongta RP850-USE 80mm Thermal Receipt Printer (USB, Serial, Ethernet)',
    img: 'https://ryans.com/storage/products/main/rongta-rp850-use-80mm-thermal-receipt-printer-11720344486.webp',
    type: 'Inkjet',
    color: 'Color',
    connectivity: 'USB',
    price: 14000,
  },
  {
    id: 5,
    name: 'Rongta RP327-UP Thermal POS Receipt Printer (USB, Parallel)',
    img: 'https://ryans.com/storage/products/main/rongta-rp327-up-thermal-receipt-printer-usb-11562747025.webp',
    type: 'Laser',
    color: 'Black & White',
    connectivity: 'Wi-Fi, USB',
    price: 19000,
  },
  {
    id: 6,
    name: 'Rongta RP330-USE Auto Cutter Low Noise Thermal POS Printer (Usb+Serial+ Ethernet)',
    img: 'https://ryans.com/storage/products/main/rongta-rp330-use-auto-cutter-low-noise-thermal-11591526520.webp',
    type: 'Laser',
    color: 'Black & White',
    connectivity: 'USB',
    price: 12000,
  },
  {
    id: 7,
    name: 'Rongta RP76III Impact Dot Matrix Receipt Printer',
    img: 'https://ryans.com/storage/products/main/rongta-rp76iii-impact-dot-11638100679.webp',
    type: 'Laser',
    color: 'Black & White',
    connectivity: 'USB',
    price: 18000,
  },
  {
    id: 8,
    name: 'Rongta RPP300BU Portable Mini 80mm Pocket Mobile POS Thermal Receipt Printer with Bluetooth+USB interfaces (Orange-Black Color)',
    img: 'https://www.ryans.com/storage/products/small/rongta-rpp300bu-portable-mini-80mm-pocket-mobile-11722152111.webp',
    type: 'Inkjet',
    color: 'Color',
    connectivity: 'USB',
    price: 8000,
  },
  {
    id: 9,
    name: 'Zebra ZC300 Dual-Sided Card Printer ',
    img: 'https://ryans.com/storage/products/main/zebra-zc300-dual-sided-card-printer-without-11582192079.webp',
    type: 'Inkjet',
    color: 'Color',
    connectivity: 'Wi-Fi, USB',
    price: 95000,
  },
  {
    id: 10,
    name: 'HP DesignJet T830 24-in Multifunction Printer (F9A28B)',
    img: 'https://ryans.com/storage/products/main/hp-designjet-t830-24-in-multifunction-printer-11550572286.webp',
    type: 'Laser',
    color: 'Color',
    connectivity: 'Wi-Fi, Ethernet, USB',
    price: 235000,
  },
];

// Casings data
export const casingsData = [
  {
    id: 1,
    name: 'Fantech TYPHOON FB302 Addressable RGB Case Fan',
    img: 'https://www.startech.com.bd/image/cache/catalog/casing-cooler/fantech/typhoon-fb302/typhoon-fb302-01-228x228.webp',
    formFactor: 'ATX Mid Tower',
    material: 'Steel',
    price: 7000,
  },
  {
    id: 2,
    name: 'Aigo DarkFlash DR12 Pro 3-in-1 RGB Case Fan',
    img: 'https://www.startech.com.bd/image/cache/catalog/casing-cooler/aigo/darkflash-dr12-pro/darkflash-dr12-pro-01-228x228.webp',
    formFactor: 'Micro ATX',
    material: 'Steel, Plastic',
    price: 5000,
  },
  {
    id: 3,
    name: 'NZXT F120 RGB 120mm Casing Fan',
    img: 'https://www.startech.com.bd/image/cache/catalog/casing-cooler/nzxt/f120rgb/f120rgb-01-228x228.webp',
    formFactor: 'ATX Mid Tower',
    material: 'Tempered Glass',
    price: 9000,
  },
  {
    id: 4,
    name: 'Antec Neon 120 ARGB 3 in 1 Pack Casing Fan with Controller',
    img: 'https://www.startech.com.bd/image/cache/catalog/casing-cooler/antec/neon-120-argb-3-in-1-pack/neon-120-pwm-argb-3-in-1-pack-01-228x228.webp',
    formFactor: 'ATX Mid Tower',
    material: 'Steel',
    price: 8500,
  },
  {
    id: 5,
    name: 'DeepCool FC120 WHITE 3-in-1 Performance 120mm ARGB PWM Case Fan',
    img: 'https://www.startech.com.bd/image/cache/catalog/casing-cooler/deepcool/fc120-3-in-1/fc120-white-3-in-1-01-228x228.webp',
    formFactor: 'ATX Mid Tower',
    material: 'Mesh, Steel',
    price: 9500,
  },
  {
    id: 6,
    name: 'Deepcool MF120 GT 3 IN 1 Casing Fan',
    img: 'https://www.startech.com.bd/image/cache/catalog/casing-cooler/deepcool/mf120-gt/mf120-gt-01-228x228.jpg',
    formFactor: 'ATX Mid Tower',
    material: 'Steel, Acrylic',
    price: 10000,
  },
  {
    id: 7,
    name: 'ASUS TUF Gaming TF120 ARGB White Triple Casing Fan Kit with ARGB Controller',
    img: 'https://www.startech.com.bd/image/cache/catalog/casing-cooler/asus/tuf-gaming-tf120-argb-white/tuf-gaming-tf120-argb-white-01-228x228.webp',
    formFactor: 'ATX Mid Tower',
    material: 'Steel, Tempered Glass',
    price: 9000,
  },
  {
    id: 8,
    name: 'Gamdias AEOLUS M3-1204R ARGB Casing Fan',
    img: 'https://www.startech.com.bd/image/cache/catalog/casing-cooler/gamdias/aeolus-m3-1204r/aeolus-m3-1204r-01-228x228.webp',
    formFactor: 'ATX Mid Tower',
    material: 'Steel, Plastic',
    price: 9500,
  },
  {
    id: 9,
    name: 'Lian Li UNI FAN SL-INFINITY 120mm ARGB Case Fan Triple Pack White',
    img: 'https://www.startech.com.bd/image/cache/catalog/casing-cooler/lian-li/uni-fan-sl-infinity/uni-fan-sl-infinity-triple-pack-02-228x228.webp',
    formFactor: 'ATX Mid Tower',
    material: 'Steel, Tempered Glass',
    price: 6500,
  },
  {
    id: 10,
    name: 'Lian Li UNI FAN SL V2 120 ARGB Case Fan Triple Pack White',
    img: 'https://www.startech.com.bd/image/cache/catalog/casing-cooler/lian-li/uni-fan-sl-v2-120/uni-fan-sl-v2-120-triple-pack-white-01-228x228.webp',
    formFactor: 'ATX Mid Tower',
    material: 'Steel, Mesh',
    price: 6000,
  },
];

// Mouse data
export const mouseData = [
  {
    id: 1,
    name: 'Havit MS959 RGB Backlit Programmable Gaming Mouse',
    img: 'https://www.startech.com.bd/image/cache/catalog/mouse/havit/ms959/ms959-01-228x228.webp',
    dpi: '16000',
    connection: 'Wired',
    price: 4500,
  },
  {
    id: 2,
    name: 'Rapoo 8000M Multi-mode Wireless Keyboard and Mouse Combo',
    img: 'https://www.startech.com.bd/image/cache/catalog/keyboard/rapoo/8000m/8000m-01-228x228.webp',
    dpi: '20000',
    connection: 'Wired',
    price: 5000,
  },
  {
    id: 3,
    name: 'Ajazz Aj380R RGB Gaming Mouse',
    img: 'https://www.startech.com.bd/image/cache/catalog/mouse/ajazz/aj380r/aj380r-02-228x228.webp',
    dpi: '12000',
    connection: 'Wired',
    price: 6000,
  },
  {
    id: 4,
    name: 'Logitech G402 Hyperion Fury ULTRA-FAST FPS GAMING MOUSE',
    img: 'https://www.startech.com.bd/image/cache/catalog/mouse/logitech/g402/logitech-g402-1-228x228.jpg',
    dpi: '18000',
    connection: 'Wireless',
    price: 7000,
  },
  {
    id: 5,
    name: 'Meetion MT-M985 10 buttons Programmable Wired Metal Mechanical Gaming Mouse',
    img: 'https://www.startech.com.bd/image/cache/catalog/mouse/meetion/mt-m985/mt-m985-228x228.jpeg',
    dpi: '16000',
    connection: 'Wired',
    price: 6000,
  },
  {
    id: 6,
    name: 'Keychron M1 Ultra-Light Optical Mouse',
    img: 'https://www.startech.com.bd/image/cache/catalog/mouse/keychron/keychron-m1/m1-white-01-228x228.jpg',
    dpi: '16000',
    connection: 'Wireless',
    price: 9000,
  },
  {
    id: 7,
    name: 'Vertux Phoenix Extreme Performance Professional Gaming LumiFlux Mouse',
    img: 'https://www.startech.com.bd/image/cache/catalog/mouse/vertux/phoenix/vertux-phoenix-gaming-lumiflux-mouse-01-228x228.png',
    dpi: '12000',
    connection: 'Wired',
    price: 5500,
  },
  {
    id: 8,
    name: 'Fantech HELIOS XD3 Pro Sakura Edition Wireless Gaming Mouse',
    img: 'https://www.startech.com.bd/image/cache/catalog/mouse/fantech/helios-xd3/helios-xd3-0001-228x228.jpg',
    dpi: '16000',
    connection: 'Wired',
    price: 5000,
  },
  {
    id: 9,
    name: 'Razer Basilisk V3 Pro RGB Ergonomic Wireless Gaming Mouse (Global)',
    img: 'https://www.startech.com.bd/image/cache/catalog/mouse/razer/basilisk-v3-pro/basilisk-v3-pro-01-228x228.webp',
    dpi: '18000',
    connection: 'Wired',
    price: 6500,
  },
  {
    id: 10,
    name: 'Logitech G502 X PLUS LIGHTSPEED Wireless Hero RGB Gaming Mouse White',
    img: 'https://www.startech.com.bd/image/cache/catalog/mouse/logitech/g502x/g502x-white-228x228.webp',
    dpi: '18000',
    connection: 'Wired',
    price: 7000,
  },
];

// UPS data
export const upsData = [
  {
    id: 1,
    name: 'KSTAR 3000VA Line Interactive Offline UPS',
    img: 'https://www.startech.com.bd/image/cache/catalog/ups/kstar/3000va/3000va-228x228.webp',
    capacity: '1500VA',
    outlets: 10,
    price: 20000,
  },
  {
    id: 2,
    name: 'KSTAR HP Series 1000VA Online UPS',
    img: 'https://www.startech.com.bd/image/cache/catalog/ups/kstar/hp-series-1000va/hp-series-1000va-01-228x228.webp',
    capacity: '1500VA',
    outlets: 10,
    price: 18000,
  },
  {
    id: 3,
    name: 'Power Pac 2000VA Offline UPS',
    img: 'https://www.startech.com.bd/image/cache/catalog/ups/power-pac/powerpac-228x228.webp',
    capacity: '1500VA',
    outlets: 8,
    price: 16000,
  },
  {
    id: 4,
    name: 'Apollo 2000VA Offline UPS',
    img: 'https://www.startech.com.bd/image/cache/catalog/ups/apollo/apollo-2000va/apollo-2000va-228x228.webp',
    capacity: '1000VA',
    outlets: 6,
    price: 12000,
  },
  {
    id: 5,
    name: 'KSTAR 1500VA Offline UPS',
    img: 'https://www.startech.com.bd/image/cache/catalog/ups/kstar/1500va/1500va-228x228.webp',
    capacity: '1000VA',
    outlets: 8,
    price: 8000,
  },
  {
    id: 6,
    name: 'Digital X 650VA Offline UPS',
    img: 'https://www.startech.com.bd/image/cache/catalog/ups/digital-x/650va/650va-228x228.jpg',
    capacity: '500VA',
    outlets: 6,
    price: 3000,
  },
  {
    id: 7,
    name: 'Apollo 2100HS 1000VA Online UPS',
    img: 'https://www.startech.com.bd/image/cache/catalog/ups/apollo/2100hs/2100hs-01-228x228.webp',
    capacity: '1500VA',
    outlets: 8,
    price: 28000,
  },
  {
    id: 8,
    name: 'MaxGreen MGOE-W3KS 3KVA Standard Backup Online UPS',
    img: 'https://www.startech.com.bd/image/cache/catalog/ups/maxgreen/1kva/1kva-228x228.webp',
    capacity: '1500VA',
    outlets: 10,
    price: 22000,
  },
  {
    id: 9,
    name: 'Zigor Volga NG+3 3KVA Online UPS',
    img: 'https://www.startech.com.bd/image/cache/catalog/ups/zigor/volga-ng+2/volga-ng+2-228x228.jpg',
    capacity: '600VA',
    outlets: 4,
    price: 36000,
  },
  {
    id: 10,
    name: 'SANTAK Castle 3KS 3000VA Standard Backup Online UPS',
    img: 'https://www.startech.com.bd/image/cache/catalog/ups/santak/c2k/c2k-01-228x228.jpg',
    capacity: '1500VA',
    outlets: 8,
    price: 40000,
  },
];
export const speakersData = [
  {
    id: 1,
    name: 'Logitech Z313 2:1 Speaker #980-000413',
    img: 'https://www.ryans.com/storage/products/small/logitech-z313-21-speaker-11724648315.webp',
    type: 'Portable Bluetooth Speaker',
    power: '20W',
    price: 4000,
  },
  {
    id: 2,
    name: 'CMX HSK-15T 15W White Horn Speaker',
    img: 'https://www.ryans.com/storage/products/small/cmx-hsk-15t-15w-white-horn-11706070934.webp',
    type: 'Portable Bluetooth Speaker',
    power: '16W',
    price: 4800,
  },
  {
    id: 3,
    name: 'Microlab M-300U 2:1 Speaker',
    img: 'https://ryans.com/storage/products/main/microlab-tmn9-bt-21-bluetooth-black-multimedia-11708775247.webp',
    type: 'Portable Bluetooth Speaker',
    power: '20W',
    price: 5000,
  },
  {
    id: 4,
    name: 'Microlab TMN1 2:1 Multimedia Speaker',
    img: 'https://www.ryans.com/storage/products/small/microlab-tmn1-21-11568176184.webp',
    type: 'Portable Bluetooth Speaker',
    power: '8W',
    price: 5600,
  },
  {
    id: 5,
    name: 'JBL Wind 3 Black Portable Bluetooth Speaker',
    img: 'https://www.ryans.com/storage/products/small/jbl-wind-3-black-portable-bluetooth-11707140617.webp',
    type: 'Portable Bluetooth Speaker',
    power: '12W',
    price: 5600,
  },
  {
    id: 6,
    name: 'Anker Soundcore Flare 2 Black Portable Bluetooth Speaker',
    img: 'https://ryans.com/storage/products/main/anker-soundcore-a3165g11-flare-2-black-portable-11679485116.webp',
    type: 'Portable Bluetooth Speaker',
    power: '20W',
    price: 7000,
  },
  {
    id: 7,
    name: 'F&D A521X 2:1 Bluetooth Speaker',
    img: 'https://www.ryans.com/storage/products/small/fd-a521x-21-bluetooth-11724218007.webp',
    type: 'Portable Bluetooth Speaker',
    power: '20W',
    price: 7000,
  },
  {
    id: 8,
    name: 'Microlab FC330BT 2:1 Bluetooth Wooden Multimedia Speaker',
    img: 'https://ryans.com/storage/products/main/microlab-fc330bt-21-bluetooth-wooden-multimedia-11708765971.webp',
    type: 'Portable Bluetooth Speaker',
    power: '30W',
    price: 19000,
  },
  {
    id: 9,
    name: 'Microlab T10 2:1 Gaming Bluetooth Speaker',
    img: 'https://ryans.com/storage/products/main/microlab-t10-21-gaming-bluetooth-11543645965.webp',
    type: 'Portable Bluetooth Speaker',
    power: '50W',
    price: 22000,
  },
  {
    id: 10,
    name: 'Microlab TMN1 BT 4:1 Bluetooth Multimedia Speaker',
    img: 'https://ryans.com/storage/products/main/microlab-tmn1-bt-41-bluetooth-multimedia-11708693365.webp',
    type: 'Portable Bluetooth Speaker',
    power: '100W',
    price: 25000,
  },
];
export const powerSupplyData = [
  {
    id: 1,
    name: 'Gamdias HELIOS M1-650B 650W 80 Plus Bronze Power Supply',
    img: 'https://www.startech.com.bd/image/cache/catalog/power-supply/gamdias/helios-m1-650b/helios-m1-650b-01-228x228.webp',
    wattage: '850W',
    efficiency: '80 Plus Gold',
    price: 12000,
  },
  {
    id: 2,
    name: 'Huntkey GS800 Prime 700W 80+ Bronze Power Supply',
    img: 'https://www.startech.com.bd/image/cache/catalog/power-supply/huntkey/gs800-prime/gs800-prime-01-228x228.webp',
    wattage: '750W',
    efficiency: '80 Plus Gold',
    price: 10000,
  },
  {
    id: 3,
    name: 'Antec ATOM B750 750W 80 Plus Bronze Power Supply',
    img: 'https://www.startech.com.bd/image/cache/catalog/power-supply/Antec/atom-b750/atom-b750-01-228x228.webp',
    wattage: '750W',
    efficiency: '80 Plus Gold',
    price: 11000,
  },
  {
    id: 4,
    name: '1STPLAYER STEAMPUNK 750W 80+ Gold Power Supply',
    img: 'https://www.startech.com.bd/image/cache/catalog/power-supply/1stplayer/steampunk-750w/steampunk-750w-01-228x228.webp',
    wattage: '750W',
    efficiency: '80 Plus Gold',
    price: 9500,
  },
  {
    id: 5,
    name: 'DeepCool PN650M 650W 80 Plus Gold Fully Modular Power Supply',
    img: 'https://www.startech.com.bd/image/cache/catalog/power-supply/deepcool/pn850m/pn850m-01-228x228.webp',
    wattage: '750W',
    efficiency: '80 Plus Gold',
    price: 10500,
  },
  {
    id: 6,
    name: 'Thermaltake Toughpower GF 750W 80 Plus Gold Fully Modular Power Supply',
    img: 'https://www.startech.com.bd/image/cache/catalog/power-supply/thermaltake/toughpower-gf1-750w/toughpower-gf1-750w-228x228.jpg',
    wattage: '750W',
    efficiency: '80 Plus Gold',
    price: 11500,
  },
  {
    id: 7,
    name: 'FSP Hydro K PRO 750W 80 Plus Bronze Power Supply',
    img: 'https://www.startech.com.bd/image/cache/catalog/power-supply/fsp/hydro-k-pro-500w/hydro-k-pro-500w-228x228.webp',
    wattage: '850W',
    efficiency: '80 Plus Gold',
    price: 12500,
  },
  {
    id: 8,
    name: 'DeepCool PN750M 750W 80 Plus Gold Fully Modular Power Supply',
    img: 'https://www.startech.com.bd/image/cache/catalog/power-supply/deepcool/dq850m-v3l/dq850m-v3l-01-228x228.webp',
    wattage: '750W',
    efficiency: '80 Plus Gold',
    price: 9700,
  },
  {
    id: 9,
    name: 'Gigabyte GP-P650G 650W 80 Plus Gold ATX Power Supply',
    img: 'https://www.startech.com.bd/image/cache/catalog/power-supply/gigabyte/gp-p650g/gp-p650g-01-228x228.webp',
    wattage: '750W',
    efficiency: '80 Plus Gold',
    price: 10200,
  },
  {
    id: 10,
    name: 'Corsair CX750 750W 80 PLUS Bronze ATX Power Supply',
    img: 'https://www.startech.com.bd/image/cache/catalog/power-supply/corsair/cx750/cx750-01-228x228.webp',
    wattage: '850W',
    efficiency: '80 Plus Gold',
    price: 9800,
  },
];
