export const processorsData = [
  {
      id: 1,
      name: "Intel Core i9-12900K",
      img: "assets/images/processors/intel_core_i9_12900k.jpg",
      speed: "3.2 GHz",
      cacheL2: "12 MB",
      cacheL3: "30 MB",
      cores: 16,
      threads: 24,
      memorySpeed: "4800 MHz",
      price: 55000,
    },
    {
      id: 2,
      name: "AMD Ryzen 9 5900X",
      img: "assets/images/processors/amd_ryzen_9_5900x.jpg",
      speed: "3.7 GHz",
      cacheL2: "6 MB",
      cacheL3: "64 MB",
      cores: 12,
      threads: 24,
      memorySpeed: "3200 MHz",
      price: 45000,
    },
    {
      id: 3,
      name: "Intel Core i7-12700K",
      img: "assets/images/processors/intel_core_i7_12700k.jpg",
      speed: "3.6 GHz",
      cacheL2: "11 MB",
      cacheL3: "25 MB",
      cores: 12,
      threads: 20,
      memorySpeed: "4800 MHz",
      price: 42000,
    },
    {
      id: 4,
      name: "AMD Ryzen 7 5800X",
      img: "assets/images/processors/amd_ryzen_7_5800x.jpg",
      speed: "3.8 GHz",
      cacheL2: "4 MB",
      cacheL3: "32 MB",
      cores: 8,
      threads: 16,
      memorySpeed: "3200 MHz",
      price: 38000,
    },
    {
      id: 5,
      name: "Intel Core i5-12600K",
      img: "assets/images/processors/intel_core_i5_12600k.jpg",
      speed: "3.7 GHz",
      cacheL2: "9.5 MB",
      cacheL3: "20 MB",
      cores: 10,
      threads: 16,
      memorySpeed: "4800 MHz",
      price: 30000,
    },
    {
      id: 6,
      name: "AMD Ryzen 5 5600X",
      img: "assets/images/processors/amd_ryzen_5_5600x.jpg",
      speed: "3.7 GHz",
      cacheL2: "3 MB",
      cacheL3: "32 MB",
      cores: 6,
      threads: 12,
      memorySpeed: "3200 MHz",
      price: 27000,
    },
    {
      id: 7,
      name: "Intel Core i3-12100",
      img: "assets/images/processors/intel_core_i3_12100.jpg",
      speed: "3.3 GHz",
      cacheL2: "5 MB",
      cacheL3: "12 MB",
      cores: 4,
      threads: 8,
      memorySpeed: "4800 MHz",
      price: 18000,
    },
    {
      id: 8,
      name: "AMD Ryzen 3 3300X",
      img: "assets/images/processors/amd_ryzen_3_3300x.jpg",
      speed: "3.8 GHz",
      cacheL2: "2 MB",
      cacheL3: "16 MB",
      cores: 4,
      threads: 8,
      memorySpeed: "3200 MHz",
      price: 16000,
    },
    {
      id: 9,
      name: "Intel Core i9-11900K",
      img: "assets/images/processors/intel_core_i9_11900k.jpg",
      speed: "3.5 GHz",
      cacheL2: "10 MB",
      cacheL3: "16 MB",
      cores: 8,
      threads: 16,
      memorySpeed: "3200 MHz",
      price: 50000,
    },
    {
      id: 10,
      name: "AMD Ryzen 9 3950X",
      img: "assets/images/processors/amd_ryzen_9_3950x.jpg",
      speed: "3.5 GHz",
      cacheL2: "8 MB",
      cacheL3: "64 MB",
      cores: 16,
      threads: 32,
      memorySpeed: "3200 MHz",
      price: 60000,
    },
];

// data.js
export const coolersData = [
  {
    id: 1,
    name: "Cooler Master Hyper 212",
    type: "Air Cooler",
    compatibility: "Intel & AMD",
    fanSpeed: "2000 RPM",
    noiseLevel: "19 dBA",
    price: 3500,
    img: "assets/images/coolers/cooler_master_hyper_212.jpg",
    performance: 85
  },
  {
    id: 2,
    name: "Noctua NH-D15",
    type: "Air Cooler",
    compatibility: "Intel & AMD",
    fanSpeed: "1500 RPM",
    noiseLevel: "24.6 dBA",
    price: 8000,
    img: "assets/images/coolers/noctua_nh_d15.jpg",
    performance: 95
  },
  {
    id: 3,
    name: "Corsair H100i",
    type: "Liquid Cooler",
    compatibility: "Intel & AMD",
    fanSpeed: "2400 RPM",
    noiseLevel: "30 dBA",
    price: 7000,
    img: "assets/images/coolers/corsair_h100i.jpg",
    performance: 90
  },
  {
    id: 4,
    name: "Be Quiet! Dark Rock Pro 4",
    type: "Air Cooler",
    compatibility: "Intel & AMD",
    fanSpeed: "1500 RPM",
    noiseLevel: "24.3 dBA",
    price: 6500,
    img: "assets/images/coolers/be_quiet_dark_rock_pro_4.jpg",
    performance: 88
  },
  {
    id: 5,
    name: "Arctic Liquid Freezer II 240",
    type: "Liquid Cooler",
    compatibility: "Intel & AMD",
    fanSpeed: "2000 RPM",
    noiseLevel: "23.5 dBA",
    price: 6000,
    img: "assets/images/coolers/arctic_liquid_freezer_ii_240.jpg",
    performance: 92
  },
  {
    id: 6,
    name: "NZXT Kraken X63",
    type: "Liquid Cooler",
    compatibility: "Intel & AMD",
    fanSpeed: "2800 RPM",
    noiseLevel: "29 dBA",
    price: 7500,
    img: "assets/images/coolers/nzxt_kraken_x63.jpg",
    performance: 89
  },
  {
    id: 7,
    name: "DeepCool Assassin III",
    type: "Air Cooler",
    compatibility: "Intel & AMD",
    fanSpeed: "1400 RPM",
    noiseLevel: "26 dBA",
    price: 7000,
    img: "assets/images/coolers/deepcool_assassin_iii.jpg",
    performance: 87
  },
  {
    id: 8,
    name: "Thermaltake Water 3.0 ARGB",
    type: "Liquid Cooler",
    compatibility: "Intel & AMD",
    fanSpeed: "2000 RPM",
    noiseLevel: "27 dBA",
    price: 6500,
    img: "assets/images/coolers/thermaltake_water_3_0_argb.jpg",
    performance: 86
  },
  {
    id: 9,
    name: "Cooler Master MasterLiquid ML240L",
    type: "Liquid Cooler",
    compatibility: "Intel & AMD",
    fanSpeed: "2000 RPM",
    noiseLevel: "24 dBA",
    price: 5500,
    img: "assets/images/coolers/cooler_master_masterliquid_ml240l.jpg",
    performance: 85
  },
  {
    id: 10,
    name: "Scythe Mugen 5 Rev.B",
    type: "Air Cooler",
    compatibility: "Intel & AMD",
    fanSpeed: "1200 RPM",
    noiseLevel: "19.5 dBA",
    price: 4000,
    img: "assets/images/coolers/scythe_mugen_5_rev_b.jpg",
    performance: 83
  },
];
export const motherboardData = [
  {
    id: 1,
    name: 'Motherboard A',
    img: 'assets/images/motherboards/motherboard_a.jpg',
    socket: 'LGA 1151',
    chipset: 'Z490',
    formFactor: 'ATX',
    memorySlots: 4,
    maxMemory: '128 GB',
    price: 10000,
    performance: 90,
  },
  {
    id: 2,
    name: 'Motherboard B',
    img: 'assets/images/motherboards/motherboard_b.jpg',
    socket: 'AM4',
    chipset: 'B450',
    formFactor: 'Micro ATX',
    memorySlots: 2,
    maxMemory: '64 GB',
    price: 8000,
    performance: 80,
  },
  {
    id: 3,
    name: 'Motherboard C',
    img: 'assets/images/motherboards/motherboard_c.jpg',
    socket: 'LGA 1200',
    chipset: 'Z590',
    formFactor: 'ATX',
    memorySlots: 4,
    maxMemory: '128 GB',
    price: 12000,
    performance: 95,
  },
  {
    id: 4,
    name: 'Motherboard D',
    img: 'assets/images/motherboards/motherboard_d.jpg',
    socket: 'AM4',
    chipset: 'X570',
    formFactor: 'ATX',
    memorySlots: 4,
    maxMemory: '128 GB',
    price: 15000,
    performance: 93,
  },
  {
    id: 5,
    name: 'Motherboard E',
    img: 'assets/images/motherboards/motherboard_e.jpg',
    socket: 'LGA 1151',
    chipset: 'B460',
    formFactor: 'Micro ATX',
    memorySlots: 2,
    maxMemory: '64 GB',
    price: 7000,
    performance: 75,
  },
  {
    id: 6,
    name: 'Motherboard F',
    img: 'assets/images/motherboards/motherboard_f.jpg',
    socket: 'LGA 2066',
    chipset: 'X299',
    formFactor: 'ATX',
    memorySlots: 8,
    maxMemory: '256 GB',
    price: 18000,
    performance: 92,
  },
  {
    id: 7,
    name: 'Motherboard G',
    img: 'assets/images/motherboards/motherboard_g.jpg',
    socket: 'LGA 1200',
    chipset: 'H510',
    formFactor: 'Mini ITX',
    memorySlots: 2,
    maxMemory: '64 GB',
    price: 6000,
    performance: 70,
  },
  {
    id: 8,
    name: 'Motherboard H',
    img: 'assets/images/motherboards/motherboard_h.jpg',
    socket: 'AM4',
    chipset: 'B550',
    formFactor: 'ATX',
    memorySlots: 4,
    maxMemory: '128 GB',
    price: 9000,
    performance: 85,
  },
  {
    id: 9,
    name: 'Motherboard I',
    img: 'assets/images/motherboards/motherboard_i.jpg',
    socket: 'LGA 2011',
    chipset: 'C602',
    formFactor: 'E-ATX',
    memorySlots: 8,
    maxMemory: '128 GB',
    price: 20000,
    performance: 88,
  },
  {
    id: 10,
    name: 'Motherboard J',
    img: 'assets/images/motherboards/motherboard_j.jpg',
    socket: 'LGA 1150',
    chipset: 'H97',
    formFactor: 'Micro ATX',
    memorySlots: 4,
    maxMemory: '32 GB',
    price: 5000,
    performance: 65,
  },
];
// src/data.js

export const ramData = [
  {
    id: 1,
    name: 'Corsair Vengeance LPX 16GB',
    img: 'assets/images/ram/corsair_vengeance_lpx_16gb.jpg', // Update with the correct path
    capacity: '16GB',
    speed: '3200MHz',
    type: 'DDR4',
    voltage: '1.35V',
    price: 6000,
    performance: 85,
  },
  {
    id: 2,
    name: 'G.SKILL Trident Z RGB 16GB',
    img: 'assets/images/ram/gskill_trident_z_rgb_16gb.jpg', // Update with the correct path
    capacity: '16GB',
    speed: '3600MHz',
    type: 'DDR4',
    voltage: '1.35V',
    price: 8000,
    performance: 90,
  },
  {
    id: 3,
    name: 'HyperX Fury 8GB',
    img: 'assets/images/ram/hyperx_fury_8gb.jpg', // Update with the correct path
    capacity: '8GB',
    speed: '2666MHz',
    type: 'DDR4',
    voltage: '1.2V',
    price: 3000,
    performance: 75,
  },
  {
    id: 4,
    name: 'TeamGroup T-Force Vulcan 32GB',
    img: 'assets/images/ram/teamgroup_tforce_vulcan_32gb.jpg', // Update with the correct path
    capacity: '32GB',
    speed: '3200MHz',
    type: 'DDR4',
    voltage: '1.35V',
    price: 12000,
    performance: 92,
  },
  {
    id: 5,
    name: 'Patriot Viper Steel 16GB',
    img: 'assets/images/ram/patriot_viper_steel_16gb.jpg', // Update with the correct path
    capacity: '16GB',
    speed: '4400MHz',
    type: 'DDR4',
    voltage: '1.45V',
    price: 10000,
    performance: 88,
  },
  {
    id: 6,
    name: 'ADATA XPG Spectrix D60G 8GB',
    img: 'assets/images/ram/adata_xpg_spectrix_d60g_8gb.jpg', // Update with the correct path
    capacity: '8GB',
    speed: '3200MHz',
    type: 'DDR4',
    voltage: '1.35V',
    price: 3500,
    performance: 78,
  },
  {
    id: 7,
    name: 'Crucial Ballistix 16GB',
    img: 'assets/images/ram/crucial_ballistix_16gb.jpg', // Update with the correct path
    capacity: '16GB',
    speed: '3600MHz',
    type: 'DDR4',
    voltage: '1.35V',
    price: 7000,
    performance: 85,
  },
  {
    id: 8,
    name: 'Corsair Dominator Platinum RGB 32GB',
    img: 'assets/images/ram/corsair_dominator_platinum_rgb_32gb.jpg', // Update with the correct path
    capacity: '32GB',
    speed: '3200MHz',
    type: 'DDR4',
    voltage: '1.35V',
    price: 15000,
    performance: 95,
  },
  {
    id: 9,
    name: 'G.SKILL Ripjaws V 8GB',
    img: 'assets/images/ram/gskill_ripjaws_v_8gb.jpg', // Update with the correct path
    capacity: '8GB',
    speed: '2400MHz',
    type: 'DDR4',
    voltage: '1.2V',
    price: 2500,
    performance: 70,
  },
  {
    id: 10,
    name: 'Kingston HyperX Predator 32GB',
    img: 'assets/images/ram/kingston_hyperx_predator_32gb.jpg', // Update with the correct path
    capacity: '32GB',
    speed: '3600MHz',
    type: 'DDR4',
    voltage: '1.35V',
    price: 14000,
    performance: 93,
  },
];
