export const processorsData = [
  {
    id: 1,
    name: "Intel Core i9-12900K",
    img: "assets/images/processors/intel_core_i9_12900k.jpg",
    speed: "3.2 GHz",
    cacheL2: "12 MB",
    cacheL3: "30 MB",
    cores: 16,
    threads: 24,
    memorySpeed: "4800 MHz",
    price: 55000,
    thermalDesignPower: "125W",
    integratedGraphics: "Intel UHD Graphics 770",
    warranty: "3 years",
    description: "High-performance processor ideal for gaming and content creation."
  },
  {
    id: 2,
    name: "AMD Ryzen 9 5900X",
    img: "assets/images/processors/amd_ryzen_9_5900x.jpg",
    speed: "3.7 GHz",
    cacheL2: "6 MB",
    cacheL3: "64 MB",
    cores: 12,
    threads: 24,
    memorySpeed: "3200 MHz",
    price: 45000,
    thermalDesignPower: "105W",
    integratedGraphics: "No",
    warranty: "3 years",
    description: "Excellent multi-threaded performance for gaming and productivity."
  },
  {
    id: 3,
    name: "Intel Core i7-12700K",
    img: "assets/images/processors/intel_core_i7_12700k.jpg",
    speed: "3.6 GHz",
    cacheL2: "11 MB",
    cacheL3: "25 MB",
    cores: 12,
    threads: 20,
    memorySpeed: "4800 MHz",
    price: 42000,
    thermalDesignPower: "125W",
    integratedGraphics: "Intel UHD Graphics 770",
    warranty: "3 years",
    description: "A great choice for gaming and high-performance tasks."
  },
  {
    id: 4,
    name: "AMD Ryzen 7 5800X",
    img: "assets/images/processors/amd_ryzen_7_5800x.jpg",
    speed: "3.8 GHz",
    cacheL2: "4 MB",
    cacheL3: "32 MB",
    cores: 8,
    threads: 16,
    memorySpeed: "3200 MHz",
    price: 38000,
    thermalDesignPower: "105W",
    integratedGraphics: "No",
    warranty: "3 years",
    description: "Strong performance for gaming and content creation."
  },
  {
    id: 5,
    name: "Intel Core i5-12600K",
    img: "assets/images/processors/intel_core_i5_12600k.jpg",
    speed: "3.7 GHz",
    cacheL2: "9.5 MB",
    cacheL3: "20 MB",
    cores: 10,
    threads: 16,
    memorySpeed: "4800 MHz",
    price: 30000,
    thermalDesignPower: "125W",
    integratedGraphics: "Intel UHD Graphics 770",
    warranty: "3 years",
    description: "Balanced performance for gamers and creators."
  },
  {
    id: 6,
    name: "AMD Ryzen 5 5600X",
    img: "assets/images/processors/amd_ryzen_5_5600x.jpg",
    speed: "3.7 GHz",
    cacheL2: "3 MB",
    cacheL3: "32 MB",
    cores: 6,
    threads: 12,
    memorySpeed: "3200 MHz",
    price: 27000,
    thermalDesignPower: "65W",
    integratedGraphics: "No",
    warranty: "3 years",
    description: "Great value CPU for gaming and everyday tasks."
  },
  {
    id: 7,
    name: "Intel Core i3-12100",
    img: "assets/images/processors/intel_core_i3_12100.jpg",
    speed: "3.3 GHz",
    cacheL2: "5 MB",
    cacheL3: "12 MB",
    cores: 4,
    threads: 8,
    memorySpeed: "4800 MHz",
    price: 18000,
    thermalDesignPower: "60W",
    integratedGraphics: "Intel UHD Graphics 730",
    warranty: "3 years",
    description: "Affordable option for basic computing tasks."
  },
  {
    id: 8,
    name: "AMD Ryzen 3 3300X",
    img: "assets/images/processors/amd_ryzen_3_3300x.jpg",
    speed: "3.8 GHz",
    cacheL2: "2 MB",
    cacheL3: "16 MB",
    cores: 4,
    threads: 8,
    memorySpeed: "3200 MHz",
    price: 16000,
    thermalDesignPower: "65W",
    integratedGraphics: "No",
    warranty: "3 years",
    description: "Solid performance for entry-level gaming."
  },
  {
    id: 9,
    name: "Intel Core i9-11900K",
    img: "assets/images/processors/intel_core_i9_11900k.jpg",
    speed: "3.5 GHz",
    cacheL2: "10 MB",
    cacheL3: "16 MB",
    cores: 8,
    threads: 16,
    memorySpeed: "3200 MHz",
    price: 50000,
    thermalDesignPower: "125W",
    integratedGraphics: "Intel UHD Graphics 750",
    warranty: "3 years",
    description: "Top-tier performance for gaming and heavy multitasking."
  },
  {
    id: 10,
    name: "AMD Ryzen 9 3950X",
    img: "assets/images/processors/amd_ryzen_9_3950x.jpg",
    speed: "3.5 GHz",
    cacheL2: "8 MB",
    cacheL3: "64 MB",
    cores: 16,
    threads: 32,
    memorySpeed: "3200 MHz",
    price: 60000,
    thermalDesignPower: "105W",
    integratedGraphics: "No",
    warranty: "3 years",
    description: "Exceptional performance for content creation and gaming."
  },
];
// src/data.js

export const coolersData = [
  {
    id: 1,
    name: "Cooler Master Hyper 212",
    type: "Air Cooler",
    compatibility: "Intel & AMD",
    fanSpeed: "2000 RPM",
    noiseLevel: "19 dBA",
    price: 3500,
    img: "assets/images/coolers/cooler_master_hyper_212.jpg",
    performance: 85,
  },
  {
    id: 2,
    name: "Noctua NH-D15",
    type: "Air Cooler",
    compatibility: "Intel & AMD",
    fanSpeed: "1500 RPM",
    noiseLevel: "24.6 dBA",
    price: 8000,
    img: "assets/images/coolers/noctua_nh_d15.jpg",
    performance: 95,
  },
  {
    id: 3,
    name: "Corsair H100i",
    type: "Liquid Cooler",
    compatibility: "Intel & AMD",
    fanSpeed: "2400 RPM",
    noiseLevel: "30 dBA",
    price: 7000,
    img: "assets/images/coolers/corsair_h100i.jpg",
    performance: 90,
  },
  {
    id: 4,
    name: "Be Quiet! Dark Rock Pro 4",
    type: "Air Cooler",
    compatibility: "Intel & AMD",
    fanSpeed: "1500 RPM",
    noiseLevel: "24.3 dBA",
    price: 6500,
    img: "assets/images/coolers/be_quiet_dark_rock_pro_4.jpg",
    performance: 88,
  },
  {
    id: 5,
    name: "Arctic Liquid Freezer II 240",
    type: "Liquid Cooler",
    compatibility: "Intel & AMD",
    fanSpeed: "2000 RPM",
    noiseLevel: "23.5 dBA",
    price: 6000,
    img: "assets/images/coolers/arctic_liquid_freezer_ii_240.jpg",
    performance: 92,
  },
  {
    id: 6,
    name: "NZXT Kraken X63",
    type: "Liquid Cooler",
    compatibility: "Intel & AMD",
    fanSpeed: "2800 RPM",
    noiseLevel: "29 dBA",
    price: 7500,
    img: "assets/images/coolers/nzxt_kraken_x63.jpg",
    performance: 89,
  },
  {
    id: 7,
    name: "DeepCool Assassin III",
    type: "Air Cooler",
    compatibility: "Intel & AMD",
    fanSpeed: "1400 RPM",
    noiseLevel: "26 dBA",
    price: 7000,
    img: "assets/images/coolers/deepcool_assassin_iii.jpg",
    performance: 87,
  },
  {
    id: 8,
    name: "Thermaltake Water 3.0 ARGB",
    type: "Liquid Cooler",
    compatibility: "Intel & AMD",
    fanSpeed: "2000 RPM",
    noiseLevel: "27 dBA",
    price: 6500,
    img: "assets/images/coolers/thermaltake_water_3_0_argb.jpg",
    performance: 86,
  },
  {
    id: 9,
    name: "Cooler Master MasterLiquid ML240L",
    type: "Liquid Cooler",
    compatibility: "Intel & AMD",
    fanSpeed: "2000 RPM",
    noiseLevel: "24 dBA",
    price: 5500,
    img: "assets/images/coolers/cooler_master_masterliquid_ml240l.jpg",
    performance: 85,
  },
  {
    id: 10,
    name: "Scythe Mugen 5 Rev.B",
    type: "Air Cooler",
    compatibility: "Intel & AMD",
    fanSpeed: "1200 RPM",
    noiseLevel: "19.5 dBA",
    price: 4000,
    img: "assets/images/coolers/scythe_mugen_5_rev_b.jpg",
    performance: 83,
  },
];

export const motherboardData = [
  {
    id: 1,
    name: 'Motherboard A',
    img: 'assets/images/motherboards/motherboard_a.jpg',
    socket: 'LGA 1151',
    chipset: 'Z490',
    formFactor: 'ATX',
    memorySlots: 4,
    maxMemory: '128 GB',
    price: 10000,
    performance: 90,
  },
  {
    id: 2,
    name: 'Motherboard B',
    img: 'assets/images/motherboards/motherboard_b.jpg',
    socket: 'AM4',
    chipset: 'B450',
    formFactor: 'Micro ATX',
    memorySlots: 2,
    maxMemory: '64 GB',
    price: 8000,
    performance: 80,
  },
  {
    id: 3,
    name: 'Motherboard C',
    img: 'assets/images/motherboards/motherboard_c.jpg',
    socket: 'LGA 1200',
    chipset: 'Z590',
    formFactor: 'ATX',
    memorySlots: 4,
    maxMemory: '128 GB',
    price: 12000,
    performance: 95,
  },
  {
    id: 4,
    name: 'Motherboard D',
    img: 'assets/images/motherboards/motherboard_d.jpg',
    socket: 'AM4',
    chipset: 'X570',
    formFactor: 'ATX',
    memorySlots: 4,
    maxMemory: '128 GB',
    price: 15000,
    performance: 93,
  },
  {
    id: 5,
    name: 'Motherboard E',
    img: 'assets/images/motherboards/motherboard_e.jpg',
    socket: 'LGA 1151',
    chipset: 'B460',
    formFactor: 'Micro ATX',
    memorySlots: 2,
    maxMemory: '64 GB',
    price: 7000,
    performance: 75,
  },
  {
    id: 6,
    name: 'Motherboard F',
    img: 'assets/images/motherboards/motherboard_f.jpg',
    socket: 'LGA 2066',
    chipset: 'X299',
    formFactor: 'ATX',
    memorySlots: 8,
    maxMemory: '256 GB',
    price: 18000,
    performance: 92,
  },
  {
    id: 7,
    name: 'Motherboard G',
    img: 'assets/images/motherboards/motherboard_g.jpg',
    socket: 'LGA 1200',
    chipset: 'H510',
    formFactor: 'Mini ITX',
    memorySlots: 2,
    maxMemory: '64 GB',
    price: 6000,
    performance: 70,
  },
  {
    id: 8,
    name: 'Motherboard H',
    img: 'assets/images/motherboards/motherboard_h.jpg',
    socket: 'AM4',
    chipset: 'B550',
    formFactor: 'ATX',
    memorySlots: 4,
    maxMemory: '128 GB',
    price: 9000,
    performance: 85,
  },
  {
    id: 9,
    name: 'Motherboard I',
    img: 'assets/images/motherboards/motherboard_i.jpg',
    socket: 'LGA 2011',
    chipset: 'C602',
    formFactor: 'E-ATX',
    memorySlots: 8,
    maxMemory: '128 GB',
    price: 20000,
    performance: 88,
  },
  {
    id: 10,
    name: 'Motherboard J',
    img: 'assets/images/motherboards/motherboard_j.jpg',
    socket: 'LGA 1150',
    chipset: 'H97',
    formFactor: 'Micro ATX',
    memorySlots: 4,
    maxMemory: '32 GB',
    price: 5000,
    performance: 65,
  },
];
export const ramData = [
  {
    id: 1,
    name: 'Corsair Vengeance LPX 16GB',
    img: 'assets/images/ram/corsair_vengeance_lpx_16gb.jpg',
    capacity: '16GB',
    speed: '3200MHz',
    type: 'DDR4',
    voltage: '1.35V',
    channels: 'Dual Channel',
    price: 6000,
    performance: 85,
  },
  {
    id: 2,
    name: 'G.Skill Ripjaws V 16GB',
    img: 'assets/images/ram/gskill_ripjaws_v_16gb.jpg',
    capacity: '16GB',
    speed: '3200MHz',
    type: 'DDR4',
    voltage: '1.35V',
    channels: 'Dual Channel',
    price: 5800,
    performance: 80,
  },
  {
    id: 3,
    name: 'HyperX Fury 16GB',
    img: 'assets/images/ram/hyperx_fury_16gb.jpg',
    capacity: '16GB',
    speed: '3200MHz',
    type: 'DDR4',
    voltage: '1.35V',
    channels: 'Dual Channel',
    price: 5900,
    performance: 82,
  },
  {
    id: 4,
    name: 'Crucial Ballistix 16GB',
    img: 'assets/images/ram/crucial_ballistix_16gb.jpg',
    capacity: '16GB',
    speed: '3200MHz',
    type: 'DDR4',
    voltage: '1.35V',
    channels: 'Dual Channel',
    price: 5700,
    performance: 78,
  },
  {
    id: 5,
    name: 'Team T-Force Vulcan Z 16GB',
    img: 'assets/images/ram/team_tforce_vulcan_z_16gb.jpg',
    capacity: '16GB',
    speed: '3200MHz',
    type: 'DDR4',
    voltage: '1.35V',
    channels: 'Dual Channel',
    price: 5600,
    performance: 76,
  },
  {
    id: 6,
    name: 'Patriot Viper Steel 16GB',
    img: 'assets/images/ram/patriot_viper_steel_16gb.jpg',
    capacity: '16GB',
    speed: '3200MHz',
    type: 'DDR4',
    voltage: '1.35V',
    channels: 'Dual Channel',
    price: 5900,
    performance: 79,
  },
  {
    id: 7,
    name: 'Ballistix Max 16GB',
    img: 'assets/images/ram/ballistix_max_16gb.jpg',
    capacity: '16GB',
    speed: '3600MHz',
    type: 'DDR4',
    voltage: '1.35V',
    channels: 'Dual Channel',
    price: 6500,
    performance: 90,
  },
  {
    id: 8,
    name: 'Corsair Dominator Platinum 32GB',
    img: 'assets/images/ram/corsair_dominator_platinum_32gb.jpg',
    capacity: '32GB',
    speed: '3200MHz',
    type: 'DDR4',
    voltage: '1.35V',
    channels: 'Dual Channel',
    price: 12000,
    performance: 95,
  },
  {
    id: 9,
    name: 'G.Skill Trident Z RGB 16GB',
    img: 'assets/images/ram/gskill_trident_z_rgb_16gb.jpg',
    capacity: '16GB',
    speed: '3600MHz',
    type: 'DDR4',
    voltage: '1.35V',
    channels: 'Dual Channel',
    price: 7000,
    performance: 88,
  },
  {
    id: 10,
    name: 'ADDMEM 16GB 3200MHz',
    img: 'assets/images/ram/addmem_16gb_3200mhz.jpg',
    capacity: '16GB',
    speed: '3200MHz',
    type: 'DDR4',
    voltage: '1.35V',
    channels: 'Dual Channel',
    price: 5500,
    performance: 75,
  },
];
export const storageData = [
  {
    id: 1,
    name: 'Samsung 970 EVO Plus 1TB',
    img: 'assets/images/storage/samsung_970_evo_plus_1tb.jpg',
    type: 'SSD',
    capacity: '1TB',
    readSpeed: '3500 MB/s',
    writeSpeed: '3300 MB/s',
    interface: 'NVMe',
    price: 12000,
    performance: 95,
  },
  {
    id: 2,
    name: 'Crucial MX500 500GB',
    img: 'assets/images/storage/crucial_mx500_500gb.jpg',
    type: 'SSD',
    capacity: '500GB',
    readSpeed: '560 MB/s',
    writeSpeed: '510 MB/s',
    interface: 'SATA III',
    price: 6000,
    performance: 80,
  },
  {
    id: 3,
    name: 'Western Digital Blue 1TB',
    img: 'assets/images/storage/western_digital_blue_1tb.jpg',
    type: 'HDD',
    capacity: '1TB',
    readSpeed: '150 MB/s',
    writeSpeed: '140 MB/s',
    interface: 'SATA III',
    price: 4000,
    performance: 70,
  },
  {
    id: 4,
    name: 'Seagate Barracuda 2TB',
    img: 'assets/images/storage/seagate_barracuda_2tb.jpg',
    type: 'HDD',
    capacity: '2TB',
    readSpeed: '180 MB/s',
    writeSpeed: '170 MB/s',
    interface: 'SATA III',
    price: 5000,
    performance: 75,
  },
  {
    id: 5,
    name: 'Kingston A2000 1TB',
    img: 'assets/images/storage/kingston_a2000_1tb.jpg',
    type: 'SSD',
    capacity: '1TB',
    readSpeed: '2200 MB/s',
    writeSpeed: '2000 MB/s',
    interface: 'NVMe',
    price: 9000,
    performance: 85,
  },
  {
    id: 6,
    name: 'SanDisk SSD PLUS 480GB',
    img: 'assets/images/storage/sandisk_ssd_plus_480gb.jpg',
    type: 'SSD',
    capacity: '480GB',
    readSpeed: '535 MB/s',
    writeSpeed: '450 MB/s',
    interface: 'SATA III',
    price: 5000,
    performance: 78,
  },
  {
    id: 7,
    name: 'Toshiba X300 4TB',
    img: 'assets/images/storage/toshiba_x300_4tb.jpg',
    type: 'HDD',
    capacity: '4TB',
    readSpeed: '190 MB/s',
    writeSpeed: '180 MB/s',
    interface: 'SATA III',
    price: 8000,
    performance: 72,
  },
  {
    id: 8,
    name: 'Samsung 860 EVO 1TB',
    img: 'assets/images/storage/samsung_860_evo_1tb.jpg',
    type: 'SSD',
    capacity: '1TB',
    readSpeed: '550 MB/s',
    writeSpeed: '520 MB/s',
    interface: 'SATA III',
    price: 10000,
    performance: 90,
  },
  {
    id: 9,
    name: 'WD Blue 500GB',
    img: 'assets/images/storage/wd_blue_500gb.jpg',
    type: 'HDD',
    capacity: '500GB',
    readSpeed: '150 MB/s',
    writeSpeed: '140 MB/s',
    interface: 'SATA III',
    price: 3000,
    performance: 68,
  },
  {
    id: 10,
    name: 'Seagate FireCuda 2TB',
    img: 'assets/images/storage/seagate_firecuda_2tb.jpg',
    type: 'SSD',
    capacity: '2TB',
    readSpeed: '5400 MB/s',
    writeSpeed: '5000 MB/s',
    interface: 'NVMe',
    price: 15000,
    performance: 92,
  },
];
export const gpusData = [
  {
    id: 1,
    name: 'NVIDIA GeForce RTX 3060',
    img: 'assets/images/gpus/rtx_3060.jpg',
    memory: '12GB',
    coreClock: '1320 MHz',
    boostClock: '1777 MHz',
    cudaCores: '3584',
    interface: 'PCIe 4.0',
    price: 30000,
    performance: 90,
  },
  {
    id: 2,
    name: 'AMD Radeon RX 6700 XT',
    img: 'assets/images/gpus/radeon_rx_6700_xt.jpg',
    memory: '12GB',
    coreClock: '2321 MHz',
    boostClock: '2581 MHz',
    cudaCores: '2560',
    interface: 'PCIe 4.0',
    price: 35000,
    performance: 92,
  },
  {
    id: 3,
    name: 'NVIDIA GeForce RTX 3070',
    img: 'assets/images/gpus/rtx_3070.jpg',
    memory: '8GB',
    coreClock: '1500 MHz',
    boostClock: '1725 MHz',
    cudaCores: '5888',
    interface: 'PCIe 4.0',
    price: 40000,
    performance: 95,
  },
  {
    id: 4,
    name: 'AMD Radeon RX 6800',
    img: 'assets/images/gpus/radeon_rx_6800.jpg',
    memory: '16GB',
    coreClock: '1815 MHz',
    boostClock: '2105 MHz',
    cudaCores: '3840',
    interface: 'PCIe 4.0',
    price: 50000,
    performance: 93,
  },
  {
    id: 5,
    name: 'NVIDIA GeForce RTX 3080',
    img: 'assets/images/gpus/rtx_3080.jpg',
    memory: '10GB',
    coreClock: '1440 MHz',
    boostClock: '1710 MHz',
    cudaCores: '8704',
    interface: 'PCIe 4.0',
    price: 70000,
    performance: 98,
  },
  {
    id: 6,
    name: 'AMD Radeon RX 6900 XT',
    img: 'assets/images/gpus/radeon_rx_6900_xt.jpg',
    memory: '16GB',
    coreClock: '1825 MHz',
    boostClock: '2250 MHz',
    cudaCores: '5120',
    interface: 'PCIe 4.0',
    price: 80000,
    performance: 96,
  },
  {
    id: 7,
    name: 'NVIDIA GeForce RTX 3050',
    img: 'assets/images/gpus/rtx_3050.jpg',
    memory: '8GB',
    coreClock: '1550 MHz',
    boostClock: '1777 MHz',
    cudaCores: '2048',
    interface: 'PCIe 4.0',
    price: 25000,
    performance: 85,
  },
  {
    id: 8,
    name: 'AMD Radeon RX 5600 XT',
    img: 'assets/images/gpus/radeon_rx_5600_xt.jpg',
    memory: '6GB',
    coreClock: '1375 MHz',
    boostClock: '1560 MHz',
    cudaCores: '2304',
    interface: 'PCIe 4.0',
    price: 20000,
    performance: 80,
  },
  {
    id: 9,
    name: 'NVIDIA GeForce GTX 1660 Super',
    img: 'assets/images/gpus/gtx_1660_super.jpg',
    memory: '6GB',
    coreClock: '1530 MHz',
    boostClock: '1785 MHz',
    cudaCores: '1408',
    interface: 'PCIe 3.0',
    price: 18000,
    performance: 75,
  },
  {
    id: 10,
    name: 'AMD Radeon RX 5500 XT',
    img: 'assets/images/gpus/radeon_rx_5500_xt.jpg',
    memory: '4GB',
    coreClock: '1607 MHz',
    boostClock: '1845 MHz',
    cudaCores: '1408',
    interface: 'PCIe 4.0',
    price: 15000,
    performance: 70,
  },
];
